name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: setup deps
      run: |
        sudo apt-get update
        sudo apt-get install gcc g++ cmake uncrustify valgrind libzip-dev
    - name: show compiler version
      run: g++ --version
    - name: isolate-build
      run: mkdir build
    - name: generate build environment
      working-directory: ./build
      run: cmake ..
    - name: make the project
      working-directory: ./build
      run: make
    - name: test
      working-directory: ./build
      run: make test
